services:
  - type: web
    name: fake-job-detection
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python -c \"import nltk; nltk.download('stopwords'); nltk.download('wordnet'); nltk.download('omw-1.4')\""
    startCommand: "gunicorn app:app"
